redis:
- chartVersion: '1.4'
  env: cluster1
  name: gateway-perimeter-cluster1
  namespace: perimeter
  overrides:
    maxdbsize: 50MiMiMi
  template: tyk
  usergroup: 67a8c9065511b30001a8faf3
- chartVersion: '1.4'
  env: cluster1
  name: gateway-perimeter-cluster1
  namespace: perimeter
  overrides:
    maxdbsize: 50MiMi
  template: tyk
  usergroup: 67a8c9085511b30001a8faf4
- chartVersion: '1.4'
  env: cluster1
  name: gateway-perimeter-cluster1
  namespace: perimeter
  overrides:
    maxdbsize: 50Mi
  template: tyk
  usergroup: 67a8c9715511b30001a8faf5
