redis:
- chartVersion: '1.4'
  env: cluster1
  name: gateway-perimeter-cluster1
  namespace: perimeter
  overrides:
    maxdbsize: 50MiMi
  template: tyk
  usergroup: 67a8caa55511b30001a8faf7
- chartVersion: '1.4'
  env: cluster1
  name: gateway-perimeter-cluster1
  namespace: perimeter
  overrides:
    maxdbsize: 50Mi
  template: tyk
  usergroup: 67a8caa75511b30001a8faf8
